"""baseline: users / strategies / strategy_versions / backtest_runs / backtest_results / trade_groups / trade_executions / daily_equity

Revision ID: 32f5636ac93e
Revises: 
Create Date: 2026-05-09 22:35:33.604818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32f5636ac93e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('strategy_json', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('favorite', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategies_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategies_user_id'), ['user_id'], unique=False)

    op.create_table('backtest_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('run_name', sa.String(length=200), nullable=False),
    sa.Column('strategy_snapshot_json', sa.JSON(), nullable=False),
    sa.Column('universe_config_json', sa.JSON(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('initial_cash', sa.Float(), nullable=False),
    sa.Column('fee_rate', sa.Float(), nullable=False),
    sa.Column('tax_rate_json', sa.JSON(), nullable=False),
    sa.Column('slippage', sa.Float(), nullable=False),
    sa.Column('execution_price_type', sa.String(length=50), nullable=False),
    sa.Column('use_adjusted_price', sa.Boolean(), nullable=False),
    sa.Column('tick_rounding', sa.String(length=50), nullable=False),
    sa.Column('priority_method', sa.String(length=50), nullable=False),
    sa.Column('priority_tie_breaker', sa.String(length=50), nullable=False),
    sa.Column('random_seed', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='backteststatus', native_enum=False, length=20), nullable=False),
    sa.Column('progress_pct', sa.Float(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backtest_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backtest_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_backtest_runs_strategy_id'), ['strategy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_backtest_runs_user_id'), ['user_id'], unique=False)

    op.create_table('strategy_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('strategy_json', sa.JSON(), nullable=False),
    sa.Column('change_note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strategy_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategy_versions_strategy_id'), ['strategy_id'], unique=False)

    op.create_table('backtest_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('initial_cash', sa.Float(), nullable=False),
    sa.Column('final_equity', sa.Float(), nullable=False),
    sa.Column('total_return_pct', sa.Float(), nullable=False),
    sa.Column('annual_return_pct', sa.Float(), nullable=False),
    sa.Column('mdd_pct', sa.Float(), nullable=False),
    sa.Column('trade_count', sa.Integer(), nullable=False),
    sa.Column('open_position_count', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('avg_holding_days', sa.Float(), nullable=False),
    sa.Column('avg_profit_pct', sa.Float(), nullable=False),
    sa.Column('avg_loss_pct', sa.Float(), nullable=False),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_table('daily_equity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('stock_value', sa.Float(), nullable=False),
    sa.Column('total_equity', sa.Float(), nullable=False),
    sa.Column('daily_return', sa.Float(), nullable=False),
    sa.Column('cumulative_return', sa.Float(), nullable=False),
    sa.Column('drawdown', sa.Float(), nullable=False),
    sa.Column('positions_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'date', name='uq_daily_equity_run_date')
    )
    with op.batch_alter_table('daily_equity', schema=None) as batch_op:
        batch_op.create_index('ix_daily_equity_run_date', ['run_id', 'date'], unique=False)

    op.create_table('trade_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('entry_quantity', sa.Integer(), nullable=False),
    sa.Column('remaining_quantity', sa.Integer(), nullable=False),
    sa.Column('fully_closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('final_profit', sa.Float(), nullable=True),
    sa.Column('final_profit_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trade_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trade_groups_entry_date'), ['entry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_groups_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_groups_symbol'), ['symbol'], unique=False)

    op.create_table('trade_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_group_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('execution_date', sa.Date(), nullable=False),
    sa.Column('execution_type', sa.Enum('BUY', 'SELL', 'PARTIAL_SELL', name='tradeexecutiontype', native_enum=False, length=20), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('gross_amount', sa.Float(), nullable=False),
    sa.Column('fee', sa.Float(), nullable=False),
    sa.Column('tax', sa.Float(), nullable=False),
    sa.Column('net_amount', sa.Float(), nullable=False),
    sa.Column('realized_profit', sa.Float(), nullable=True),
    sa.Column('realized_profit_rate', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trade_group_id'], ['trade_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trade_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trade_executions_execution_date'), ['execution_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_executions_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_executions_trade_group_id'), ['trade_group_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trade_executions_trade_group_id'))
        batch_op.drop_index(batch_op.f('ix_trade_executions_run_id'))
        batch_op.drop_index(batch_op.f('ix_trade_executions_execution_date'))

    op.drop_table('trade_executions')
    with op.batch_alter_table('trade_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trade_groups_symbol'))
        batch_op.drop_index(batch_op.f('ix_trade_groups_run_id'))
        batch_op.drop_index(batch_op.f('ix_trade_groups_entry_date'))

    op.drop_table('trade_groups')
    with op.batch_alter_table('daily_equity', schema=None) as batch_op:
        batch_op.drop_index('ix_daily_equity_run_date')

    op.drop_table('daily_equity')
    op.drop_table('backtest_results')
    with op.batch_alter_table('strategy_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategy_versions_strategy_id'))

    op.drop_table('strategy_versions')
    with op.batch_alter_table('backtest_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backtest_runs_user_id'))
        batch_op.drop_index(batch_op.f('ix_backtest_runs_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_backtest_runs_status'))

    op.drop_table('backtest_runs')
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategies_user_id'))
        batch_op.drop_index(batch_op.f('ix_strategies_deleted_at'))

    op.drop_table('strategies')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
